### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by KurtzPT** [anacrolix/imdbrt#16]
Gets stuck at "Checking Rotten Tomatoes..." in every movie page.

Chrome: Version 57.0.2987.21 beta (64-bit)

**Comment by kaptainkommie** [comment]
I have the same issue.

Chrome: Version 56.0.2924.87 (32-bit)

**Comment by anacrolix** [comment]
Do you guys have adblockers?

**Comment by kaptainkommie** [comment]
I have both UBlock Origin and the Kaspersky Protection (blocks tracking/data collection, etc) addon. Turning both them off _seems_ to have no effect. While testing various combinations of UBlock/Kaspersky enabled/disabled, I have seen the rotten tomatoes requests succeed twice, most other times it just waits indefinitely. 

Is there a way to use the Network Tab in the Developer Console to see what happens to the request from the RottenTomatoes plugin?

**Comment by anacrolix** [comment]
It looks like the service I'm using to get the scores is down. http://www.omdbapi.com/

I'll copy the status message here in case it goes away:

> Attention Users!
> 
> 02/04/17 - Error 503/The service is unavailable! I KNOW! I've been working throughout the night trying to track down the bot/script/attack causing this issue, it's not normal activity as someone decided it was a good idea to open over 50+ concurrent connections and spam 300+ million requests an hour. Unfortunately the majority of features available to me to prevent these sorts of attacks are browser security checks (which are currently enabled so you can read this message) this is only temporary as I'm aware it breaks the majority of API implementations. Sorry for the inconvenience and I'll be working nonstop to get this resolved ASAP.

**Comment by kaptainkommie** [comment]
Well, that certainly explains the intermittent successes. I had assumed you were using the RottenTomatoes API directly. [https://developer.fandango.com/Rotten_Tomatoes](https://developer.fandango.com/Rotten_Tomatoes)

**Comment by anacrolix** [comment]
Maybe I should.

**Comment by kaptainkommie** [comment]
Seems to be working fine today! OMDB must have fixed the issue.

**Comment by moviedino** [comment]
i always get the error "No Score Yet..." and "No Audience Rating Yet..." allthoug they are available.
> example: http://www.imdb.com/title/tt0076759/

is there a chance to update the plugin?

**Comment by anacrolix** [comment]
I'm also getting this. Again it looks like omdb is down. I don't have a lot of time to look into it presently, I'll reassess the situation in a while.

**Comment by kaptainkommie** [comment]
I've forked the plugin. I'm curious to see if using the RottenTomatoes API directly will fix this problem. I don't have much free time either, but perhaps sometime this week I'll get a chance.

**Comment by konstantinosftw** [comment]
OMDB works because when I click on the "No Score Yet.." it redirects me to the correct RT movie page. It would seem that the extension simply does not grab the right DOM elements to present, probably RT changed its DOM.

**Comment by kaptainkommie** [comment]
I think he's using the OMDB API, not just scraping DOM elements.

**Comment by konstantinosftw** [comment]
I see that OMDB provides only a single object property in their .json, `{"Source":"Rotten Tomatoes","Value":"91%"}`, which is the score of the TOMATOMETER. So I assume he has to be scraping the RT's html code in order to grab "consensus" and all the rest.

**Comment by kaptainkommie** [comment]
http://www.omdbapi.com/?tomatoes=true&i=tt0133093

That's an example of his API request. It seems that much of the returned JSON information for rottentomatoes has 'N/A' for its value.

**Comment by kaptainkommie** [comment]
In a previous post, I had suggested transitioning to directly using the Rotten Tomatoes API might solve this type of problem. After revisiting their API site, it seems that now API Key requests are only approved on a case-by-case basis and that there is a licensing fee associated with its usage as well.

Pulled from another github issues page:

> Rotten Tomatoes is no longer issuing API keys at the time of registration. We will review each application to ensure the usage of our data aligns with Brand Guidelines and Terms of Service and will provision keys if approved. There is now a license fee to access the API details of which will be provided upon application approval. The approval process may take up to 60 days. Thank you for your patience.

**Comment by kaptainkommie** [comment]
Furthermore, it appears OMDB is closing their API to the public. If you want to continue to use the API, you will have to pay a small monthly fee:

From https://www.patreon.com/posts/api-is-going-10743518
> I need to rework all of the goals and rewards due to this change, and I hope the people dependent on this API can afford $1 a month for the time being.

**Comment by kaptainkommie** [comment]
After contacting Brian who runs the OMDB site, he directed me here for an explanation of the changes to the OMDB API response. It seems due to RT's legal team, he's had to drop many of the details he would have previously returned in the response JSON.

https://www.patreon.com/posts/rating-changes-8417367

**Comment by anacrolix** [comment]
Thanks for the feedback guys. It looks like the API may have changed a little, but the data I need is still available in the response. I'll update it in the next week, or take a PR if anyone solves it in the meanwhile.

**Comment by kaptainkommie** [comment]
PR #17 to fix the problem with no overall score displayed. The other fields that were previously used seem to no longer be provided by the OMDB API. I'm not sure if he has a patch in the works to address that, or if due to the changes to the underlying RT API, we will no longer be able to get that more detailed information.

**Comment by anacrolix** [comment]
I've merged your PR, updated from upstream, and pushed 4.0.2. At least in the meanwhile we can continue to have the RT rating. Let's see where omdbapi ends up.

**Comment by anacrolix** [comment]
It seems to be taking a while to publish 4.0.2. But I've uploaded it, let me know if it works when it (presumably) arrives.

**Comment by kaptainkommie** [comment]
Yes, it is working now.

**Comment by moviedino** [comment]
thanks so much for updating! 👍 
RT ratings are back now, but audience score is still not working.
also the tomatometer symbols are not grabbed.

**Comment by kaptainkommie** [comment]
@moviedino I wasn't aware of the tomatometer symbols not being pulled; I'll check this out, it may be related to the API changes as well. As far as your other reports, until the OMDB API gets updated, the only information available to use is just the RT Ratings. We are awaiting the fate of OMDB.

**Comment by kaptainkommie** [comment]
@moviedino It appears that these images were previously passed as a response from the API request. I'm assuming your'e talking about the icons like "certified fresh" or the splat looking one? 

While we could certainly pull these images and store them locally and run our own logic to determine which one to display, with the changes RT has made to their API and terms of use, I'm not sure the legality of using their images. Is this fair use? A safer option would be to make our own images that correspond to those in use by RT and implement those our the extension instead.

**Comment by kaptainkommie** [comment]
@anacrolix I have submitted a request to Fandango about using the Rotten Tomatoes API directly. I will update when/if I receive a response from them. Using the API directly would give us back access to the more detailed information which is no longer available from OMDB.

**Comment by moviedino** [comment]
@kaptainkommie correct, i was talking about the [tomatometer](https://www.rottentomatoes.com/about/) symbols.

here is an example of the past:
![unnamed](https://cloud.githubusercontent.com/assets/12788124/26032809/9bb5779c-389c-11e7-9c7c-2b184b24f49b.jpg)

i checked the [RT page](https://www.rottentomatoes.com/help_desk/licensing/), to my humble opinion the symbols can be used. someone only hast to request the usage for the extension.

**Comment by kaptainkommie** [comment]
@moviedino @anacrolix 
PR #18 should give us the tomatometer images back, although we should note that the logic is just a simple numeric comparison and doesn't take into account the extra qualifications required to be "certified fresh." Without access to that information, this is the best we can do for now.

**Comment by moviedino** [comment]
@kaptainkommie awesome 🥇

**Comment by anacrolix** [comment]
Included in 4.0.2.1.

**Comment by moviedino** [comment]
looks like the extension is (again) not working anymore 😢

**Comment by kaptainkommie** [comment]
Looks like OMDB is requiring the use of an API key now.

The request made in the usual way:
http://www.omdbapi.com/?tomatoes=true&i=tt0133093

Returns:
`{"Response":"False","Error":"No API key provided."}`

I never did hear back from Rotten Tomatoes about my inquiry into getting an API key for them.

**Comment by kaptainkommie** [comment]
Access to the OMDB API is now $1/month for 100,000 requests per day.

https://www.patreon.com/bePatron?u=5038490

**Comment by kaptainkommie** [comment]
@anacrolix Patch #19 fixes this issue, for now.

**Comment by anacrolix** [comment]
It's a shame we don't get all the old data points with the API key

**Comment by kaptainkommie** [comment]
Yes. I've asked on OMDB's Patreon page about those extra data points, so have other people. We haven't gotten any response from Brian who runs OMDB yet. He had previously mentioned it was Rotten Tomatoes fault, maybe he's working to resolve it.
